rootProject.name = 'monolito-modular'

include 'app'
include 'categoria'
include 'proveedor'
include 'cliente-service'
include 'subscription-service'
include 'auth'
include 'contabilidad-service'
include 'nomina'
include 'empresa-service'
include 'inventario'
include 'compra'
include 'venta-service'
